# Generated by Django 2.2.27 on 2022-05-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='type',
        ),
    ]
