from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(Account)
admin.site.register(Address)
admin.site.register(FullName)
admin.site.register(Customer)
admin.site.register(Comment)
admin.site.register(Cart)
admin.site.register(CartItem)
admin.site.register(Order)
admin.site.register(Book)
admin.site.register(Author)
admin.site.register(Publisher)
admin.site.register(ItemBook)
admin.site.register(Category)
admin.site.register(Payment)
admin.site.register(Laptop)
admin.site.register(ItemLaptop)
admin.site.register(Producer)
admin.site.register(Type)
admin.site.register(Clothes)
admin.site.register(ItemClothes)
admin.site.register(Style)
admin.site.register(Manufacture)
admin.site.register(Mobile)
admin.site.register(ItemMobile)
admin.site.register(BrandCompany)
admin.site.register(MobileType)
admin.site.register(Electronics)
admin.site.register(ItemElectronics)
admin.site.register(ElectroProducer)
admin.site.register(Kind)
admin.site.register(Shipment)
